app/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "app"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('userAuth/', include('userAuth.urls')),
    path('top/', views.top, name="top"),
    path('upload/', views.upload, name="upload"),
    path('uploadpost/', views.uploadpost, name="uploadpost"),
    path('user/', include('user.urls')),
    path('setting/', include('setting.urls')),
]

jiro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('userAuth/', include('userAuth.urls')),
    path('app/', include('app.urls')),
]

templates/app/header.html
{% load static %}
<header>
    <a href="/app/top"><img src="{% static 'img/jirosta_logo.png' %}"></a>
    <form action="{% url 'app:user:search' %}" method="post">
        <input type="text" name="search" id="search" placeholder="ユーザIDを入力して検索">
        <input type="submit" value="検索">
        {% csrf_token %}
    </form>
    <div class="menu">
        <button class="uploadBtn"><img src="/static/img/upload.png" alt="アップロード"></button>
        <a href="/app/user"><img src="/static/img/user.png" alt="ユーザ" class="avg"></a>
        <a href="/app/setting"><img src="/static/img/setting.png" alt="設定"></a>
    </div>
</header>

templates/app/modal_upload.html
{% load static %}
<div class="up_wrapper">
    <main class="upload">
        <div class="form">
            <form action="{% url 'app:uploadpost' %}" autocomplete="off" enctype="multipart/form-data" method="post">
                <div class="datawrapper">
                    <div class="data">
                        <div class="thum">
                            <label class="label">
                                <input type="file" id="file" accept="image/png, image/jpeg, image/gif" name="uploadimg" class="modal_uploadimg">
                                <img class="preview" id="modal_preview" src="{% static 'img/thum_back.png' %}" width="60px" height="60px" style="object-fit: cover;" alt="add_upload">
                            </label>
                        </div>
                    </div>
                    <div class="data">
                        <div class="text_length">
                            <label>一言</label>
                            <p class="modal_text_count">300</p>
                        </div>
                        <textarea class="modal_photo_form" name="text"></textarea>
                    </div>
                </div>
                <div class="data_submit">
                    <input type="submit" value="アップロード" class="uploadsubmit">
                    <div class="modal_data_submit_mask">
                        <div class="submit_mask"></div>
                    </div>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </main>
</div>

templates/app/top.html
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>二郎スタ</title>
        <link rel="stylesheet" href="{% static 'css/user/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/user/user.css' %}">
        <link rel="stylesheet" href="{% static 'css/user/upload.css' %}">
        <link rel="stylesheet" href="{% static 'css/css-loader.css' %}">
        <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
        <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    </head>
    <body>
        <div class="loader loader-default"></div>
            <div class="wrapper">
                {% include  "app/header.html" %}
                <div class="up-modal">
                    <div class="modal_upload">
                        <div class="closeBtn upcloseBtn"><img src="/static/img/close.png" alt="閉じる"></div>
                        {% include  "app/modal_upload.html" %}
                    </div>
                </div>
                <div class="p-modal">
                    <div class="f_content">
                        <div class="closeBtn"><img src="/static/img/close.png" alt="閉じる"></div>
                        <div class="f_header">
                            <p>フォロー</p>
                        </div>
                        {% if follow %}
                            <div class="f_list">
                                {% for i in follow.values %}
                                    <form action="{% url 'app:user:searchuser' %}" method="POST">
                                        <div class="f_user">
                                            <input type="image" src="{% static i.path %}">
                                            <input type="submit" value={{i.userid}}>
                                            <input type="hidden" name="searchid" value={{i.userid}}>
                                        </div>
                                        {% csrf_token %}
                                    </form>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="no">
                                <p>フォローなし</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="p-modal2 closeBtn2">
                    <div class="f_content">
                        <div class="closeBtn"><img src="/static/img/close.png" alt="閉じる"></div>
                        <div class="f_header">
                            <p>フォロワー</p>
                        </div>
                        {% if follower %}
                            <div class="f_list">
                                {% for i in follower.values %}
                                    <form action="{% url 'app:user:searchuser' %}" method="POST">
                                        <div class="f_user">
                                            <input type="image" src="{% static i.path %}">
                                            <input type="submit" value={{i.userid}}>
                                            <input type="hidden" name="searchid" value={{i.userid}}>
                                        </div>
                                        {% csrf_token %}
                                    </form>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="no">
                                <p>フォロワーなし</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class=sub_wrapper>
                    <main class="timeline">
                        {% comment %} {% include  "app/upload.html" %} {% endcomment %}
                        {% if list %}
                            {% for i in list.values %}
                            <div class="photo">
                                <div class="asideheader">
                                    <form action="{% url 'app:user:searchuser' %}" method="POST">
                                        <input type="image" src="{% static i.path %}" class="icon">
                                        <input type="submit" value={{i.userid}} class="user cursor">
                                        <input type="hidden" name="searchid" value={{i.userid}}>
                                        {% csrf_token %}
                                    </form>
                                </div>
                                <img src="{% static i.photo %}" class="img">
                                <div class="info">
                                    <div class="subinfo">
                                        {% if i.favorited == 0  %}
                                            <button class="fa_b {{i.id}}" id="favoriteid" value={{i.id}} onclick="Click({{i.id}});"><img src="/static/img/chashu_mask.png" class="icon fa_icon {{i.id}}_icon"></button>
                                        {% else %}
                                            <button class="fa_b {{i.id}}" id="unfavoriteid" value={{i.id}} onclick="Click({{i.id}});"><img src="/static/img/chashu.png" class="icon fa_icon {{i.id}}_icon"></button>
                                        {% endif %}
                                        <p class="fa_count {{i.id}}_count">{{ i.fa_count }}</p>
                                    </div>
                                    <p class="textView"><span class="user">{{ i.userid }}</span><span class="blog">{{ i.text | linebreaksbr }}</span></p>
                                    <p class="date">{{ i.date }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        {% else %}
                            <div class="null">
                                <div class="null_content">
                                    <img src="/static/img/null_jiro.jpg" alt="二郎の写真を投稿しよう">
                                    <h1>さぁ、今日の二郎を共有しよう</h1>
                                    <p>写真をアップロードして、ジロリアン同士で共有しよう。</p>
                                </div>
                            </div>
                        {% endif %}
                    </main>
                    <div class="user_profile">
                        {% for u in user.values %}
                            <div class="u_data">
                                <a href="/app/user"><img src="{% static u.path %}" class="pro_icon" alt="icon"></a>
                                <p><a href="/app/user">{{u.userid}}</a></p>
                            </div>
                            <div class="ff">
                                <div class="f">
                                    <label>フォロー</label>
                                    <p><span class="int p-modalBtn">{{u.follow}}人</span></p>
                                </div>
                                <div class="f">
                                    <label>フォロワー</label>
                                    <p><span class="int p-modalBtn2">{{u.follower}}人</span></p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        <script src="{% static 'js/upload.js' %}"></script>
        <script>
            $('.p-modalBtn').click(function() {
                $('.p-modal').addClass('is-open');
            })

            $('.closeBtn').click(function() {
                $('.p-modal').removeClass('is-open');
            })

            $('.p-modalBtn2').click(function() {
                $('.p-modal2').addClass('is-open');
                console.log("add");
            })

            $('.closeBtn2').click(function() {
                $('.p-modal2').removeClass('is-open');
                console.log("remove");
            })

            $('.uploadBtn').click(function() {
                $('.up-modal').addClass('is-open');
            })

            $('.upcloseBtn').click(function() {
                $('.up-modal').removeClass('is-open');
            })

            function Click(f){
                var cl = "." + f
                var id = $(cl).attr('id');
                if(id == "favoriteid"){
                    favorite(f);
                    console.log(f);
                } else if(id == "unfavoriteid"){
                    unfavorite(f);
                    console.log(f);
                }
            }

            function favorite(f) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                var csrftoken = getCookie('csrftoken');

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }

                $.ajaxSetup({
                    crossDomain: false, // obviates need for sameOrigin test
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type)) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });
                console.log(f);

                $.ajax({
                    type: 'POST',
                    url: "{% url 'app:user:favorite' %}",
                    data: "photoid=" + f
                }).done(function(data){
                    var cl = "." + f 
                    console.log(cl);
                    $(cl).removeAttr('id', 'favoriteid');
                    $(cl).attr('id', 'unfavoriteid');

                    var cl_img = "." + f + "_icon"
                    $(cl_img).removeAttr('src', '/static/img/chashu_mask.png');
                    $(cl_img).attr('src', '/static/img/chashu.png');
                    var co = data.count
                    console.log(co);
                    co = Number(co);
                    var cl2 = "." + f + "_count"
                    console.log(cl2);
                    $(cl2).html(co);
                });
                
            }

            function unfavorite(f) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                var csrftoken = getCookie('csrftoken');

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                $.ajaxSetup({
                    crossDomain: false, // obviates need for sameOrigin test
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type)) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });
                console.log(f);

                $.ajax({
                    type: 'POST',
                    url: "{% url 'app:user:unfavorite' %}",
                    data: "photoid=" + f
                }).done(function(data){
                    var cl = "." + f 
                    $(cl).removeAttr('id', 'unfavoriteid');
                    $(cl).attr('id', 'favoriteid');

                    var cl_img = "." + f + "_icon"
                    $(cl_img).removeAttr('src', '/static/img/chashu.png');
                    $(cl_img).attr('src', '/static/img/chashu_mask.png');
                    var co = data.count
                    console.log(co);
                    co = Number(co);
                    var cl2 = "." + f + "_count"
                    $(cl2).html(co);
                });
                
            }
        </script>
        
    </body>
</html>

templates/app/upload.html
{% load static %}
<div class="up_wrapper">
    <main class="upload">
        <div class="form">
            <form action="{% url 'app:uploadpost' %}" autocomplete="off" enctype="multipart/form-data" method="post">
                <div class="datawrapper">
                    <div class="data">
                        <div class="thum">
                            <label class="label">
                                <input type="file" id="file" accept="image/png, image/jpeg, image/gif" name="uploadimg" class="uploadimg">
                                <img class="preview" id="preview" src="{% static 'img/thum_back.png' %}" width="60px" height="60px" style="object-fit: cover;" alt="add_upload">
                            </label>
                        </div>
                    </div>
                    <div class="data">
                        <div class="text_length">
                            <label>一言</label>
                            <p class="text_count">300</p>
                        </div>
                        <textarea class="photo_form" name="text"></textarea>
                    </div>
                </div>
                <div class="data_submit">
                    <input type="submit" value="アップロード" class="uploadsubmit">
                    <div class="data_submit_mask">
                        <div class="submit_mask"></div>
                    </div>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </main>
</div>